name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  release: 
    types: [ created ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: ./test.sh
    - name: Get SHA
      run: echo ${{ github.sha }} && echo ${{ github.event }}